#services:
#  db:
#    image: postgres:16
#    container_name: app-postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app_db}
#      POSTGRES_USER: ${POSTGRES_USER:-app_user}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-S3curePass!}
#    ports:
#      - "5432:5432" # DataGrip ve lokal backend için
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app_user} -d ${POSTGRES_DB:-app_db}"]
#      interval: 5s
#      timeout: 5s
#      retries: 10

#  redis-cache:
#    image: redis:7-alpine
#    container_name: app-redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 10

  # backend:
  #   ... backend servisinizin geri kalanı ...
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis-cache: # <-- Backend servisinizin Redis'e de bağlı olduğundan emin olun
  #       condition: service_healthy

#volumes:
 # pgdata:

